name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build go code
      run: export CGO_ENABLED=0 && GOOS=linux &&ls && cd elb-check/elb-http-check &&  go build -v -installsuffix cgo 
      
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: elb-http-check
        path: elb-check/elb-http-check/elb-http-check

    - name: Build the Docker image
      run: |
        docker build elb-check/elb-http-check/.  --tag jenner/elb-http-check:${GITHUB_REF##*/}
        docker login -u jannanlo -p ${{secrets.DOCKERHUB}}
        docker push jenner/elb-http-check:${GITHUB_REF##*/}
